version: '3.4'

services:
 catalogb:
  container_name: catalogdb
  environment:
    - POSTGRES_USER=postegres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CatalogDb
  restart: always
  ports:
    - "5432:5432"
  volumes:
  - postgres_catlog:/var/lib/postgresql/data/